# Generated by Django 4.2 on 2023-04-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_discount_valid_from_remove_discount_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
